version: 2.1
# Define a job to be invoked later in a workflow.
jobs:
  build:
   docker:
    - image: python
   steps:
    - checkout
    - run: python Main1.py
  test:
    docker:
     - image: python
    steps:
     - checkout
     - run: python Test.py
     #orchestrate our job run sequence
workflows:
 build_ands_test:
  jobs:
   - build
   - test

